### ISSUE TITLE
Runtime for second phase

### ISSUE THREAD

**Issue by reynoldscem** [BiDiff/bidiff#3]
Hi, 

I was wondering, when doing the second phase where you fit the explicit geometry. how long is the expected runtime? Specifically when using Flexicubes.

Thanks

**Comment by DingLihe** [comment]
Hi @reynoldscem,

Thanks for your interest in our work. We only replace the neus with flexicubes in the first stage now and distill the generated flexicubes into a NeRF for the second phase refinement. For NeRF, it takes about 20 mins. Directly refining Flexicubes is more efficient than volumetric rendering and we will try it later. 

Best,
Lihe

**Comment by reynoldscem** [comment]
ah yes I see. Thank you for the reply. Best of luck with your work!
