### ISSUE TITLE
how about DDIM sampling?

### ISSUE THREAD

**Issue by thucz** [BiDiff/bidiff#6]
I wonder why DDIM sampling is not used. Is there any possibility to replace DDPM with DDIM in your method?

**Comment by DingLihe** [comment]
Dear @thucz,

We adopt the default DDPM sampling in our experiments, feel free to use DDIM or other strategies by calling different `noise_scheduler` in diffusers. Please refer to these tutorial: [https://huggingface.co/docs/diffusers/v0.27.2/en/using-diffusers/write_own_pipeline#create-random-noise](url)

**Comment by thucz** [comment]
Thanks
